@echo off
chcp 65001 >nul
echo ========================================
echo Windows Post-Install Script (.bat)
echo Generated: 04/09/2026, 22:11
echo ========================================
echo.

:: Check for Administrator privileges
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo ERROR: This script requires Administrator privileges.
    echo Please right-click and select "Run as administrator"
    echo.
    pause
    exit /b 1
)

echo Starting installation process...
echo.
::============================================
:: SOFTWARE INSTALLATION
::============================================
echo.
echo Installing selected software...
echo This may take a while depending on your internet connection.
echo.

:: Web Browsers
echo Installing Web Browsers...
echo   - Google Chrome
winget install --id Google.Chrome -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo.
echo Installing Web Browsers...
echo   - Firefox
winget install --id Mozilla.Firefox.de -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo.

:: Communication
echo Installing Communication...
echo   - Discord
winget install --id Discord.Discord -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo.

:: Media Players
echo Installing Media Players...
echo   - VLC Media Player
winget install --id VideoLAN.VLC -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo.

:: Productivity
echo Installing Productivity...
echo   - Obsidian
winget install --id Obsidian.Obsidian -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo   - Foxit PDF Reader
winget install --id Foxit.FoxitReader -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo   - PDF24
winget install --id geeksoftwareGmbH.PDF24Creator -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo   - Paint.net
winget install --id dotPDN.PaintDotNet -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log

echo.

:: Development Tools
echo Installing Development Tools...
echo   - Git
winget install --id Git.Git -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo   - Podman Desktop
winget install --id RedHat.Podman-Desktop -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo   - JetBrains Toolbox
winget install --id JetBrains.Toolbox -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo   - Visual Studio Code
winget install --id Microsoft.VisualStudioCode -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo   - mise-en-place
winget install --id jdx.mise -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo   - WinSCP
winget install --id WinSCP.WinSCP -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo   - Claude Code
powershell -Command "irm https://claude.ai/install.ps1 | iex"
echo   - Claude Desktop
winget install --id Anthropic.Claude -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo.

:: Security & Privacy
echo Installing Security & Privacy...
echo   - Bitwarden
winget install --id Bitwarden.Bitwarden -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo.

:: Cloud Storage
echo Installing Cloud Storage...
echo   - Google Drive
winget install --id Google.GoogleDrive -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo.

:: System Utilities
echo Installing System Utilities...
echo   - WinRAR
winget install --id RARLab.WinRAR -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo   - PowerToys
winget install --id Microsoft.PowerToys -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log
echo   - UniGetUI
winget install --id Devolutions.UniGetUI -e --silent --accept-package-agreements --accept-source-agreements 2>>errors.log

echo.

:: No system configurations selected
echo No system configurations selected.
echo.

::============================================
:: INSTALLATION COMPLETE
::============================================
echo.
echo ========================================
echo Installation Complete!
echo ========================================
echo.
echo If any installations failed, check errors.log
echo.
echo Next steps:
echo   1. Restart your computer if required
echo   2. Log into your installed applications
echo   3. Customize your settings as needed
echo.
echo Generated by Windows Post-Install Generator
echo https://github.com/kaic/win-post-install
echo.
pause
